package dev.langchain4j.guardrail;

import dev.langchain4j.data.message.AiMessage;
import java.util.List;

/**
 * 输出护栏
 * 输出防护栏是一条应用于模型输出的规则，旨在确保输出安全并符合预期。
 * An output guardrail is a rule that is applied to the output of the model to ensure that the output is safe and meets
 * the expectations.
 * <p>
 * 在重新提示的情况下，重新提示消息会被添加到 LLM 上下文中，并且请求会被重试。
 * In the case of reprompting, the reprompt message is added to the LLM context and the request is retried.
 * <p>
 * 最大重试次数是可配置的，默认值为 OutputGuardrailsConfig.MAX_RETRIES_DEFAULT。
 * The maximum number of retries is configurable, defaulting to {@link dev.langchain4j.guardrail.config.OutputGuardrailsConfig#MAX_RETRIES_DEFAULT}.
 */
public interface OutputGuardrail extends Guardrail<OutputGuardrailRequest, OutputGuardrailResult> {
    /**
     * 验证来自大型语言模型（LLM）的响应。
     * Validates the response from the LLM.
     *
     * @param responseFromLLM
     *            the response from the LLM
     */
    default OutputGuardrailResult validate(AiMessage responseFromLLM) {
        return failure("Validation not implemented");
    }

    /**
     * 验证来自大型语言模型（LLM）的响应。
     * Validates the response from the LLM.
     * <p>
     * 与 validate(AiMessage) 不同，这种方法允许访问内存和增强结果（在 RAG 的情况下）。
     * Unlike {@link #validate(AiMessage)}, this method allows to access the memory and the augmentation result (in the
     * case of a RAG).
     * <p>
     * 实现不得尝试写入内存或增强结果。
     * Implementation must not attempt to write to the memory or the augmentation result.
     *
     * @param request
     *            the parameters, including the response from the LLM, the memory, and the augmentation result.
     *            参数，包括来自大型语言模型的响应、聊天记忆以及增强结果。
     */
    @Override
    default OutputGuardrailResult validate(OutputGuardrailRequest request) {
        return validate(request.responseFromLLM().aiMessage());
    }

    /**
     * 产生一个没有任何成功文本的成功结果
     * Produces a successful result without any successful text
     *
     * @return The result of a successful output guardrail validation.
     */
    default OutputGuardrailResult success() {
        return OutputGuardrailResult.success();
    }

    /**
     * 产生具有特定成功文本的成功结果
     * Produces a successful result with specific success text
     *
     * @return The result of a successful output guardrail validation with a specific text.
     *
     * @param successfulText
     *            The text of the successful result.
     *            成功结果的文本
     */
    default OutputGuardrailResult successWith(String successfulText) {
        return OutputGuardrailResult.successWith(successfulText);
    }

    /**
     * 产生非致命失败
     * Produces a non-fatal failure
     *
     * @return The result of a successful output guardrail validation with a specific text.
     *
     * @param successfulText
     *            The text of the successful result.
     *            成功结果的文本
     * @param successfulResult
     *            The object generated by this successful result.
     *            由此成功结果生成的对象
     */
    default OutputGuardrailResult successWith(String successfulText, Object successfulResult) {
        return OutputGuardrailResult.successWith(successfulText, successfulResult);
    }

    /**
     * 产生具有特定成功文本的成功结果
     * Produces a successful result with specific success text
     *
     * @return The result of a successful output guardrail validation with a specific AiMessage.
     *
     * @param successfulAiMessage
     *            The AiMessage successful result.
     *            AiMessage 成功结果
     */
    default OutputGuardrailResult successWith(AiMessage successfulAiMessage) {
        return OutputGuardrailResult.successWith(successfulAiMessage);
    }

    /**
     * 产生非致命失败
     * Produces a non-fatal failure
     *
     * @param successfulAiMessage
     *            The AiMessage successful result.
     *            AiMessage 成功结果
     * @param successfulResult
     *            The object generated by this successful result.
     *            由此成功结果生成的对象
     * @return The result of a successful output guardrail validation with a specific AiMessage.
     */
    default OutputGuardrailResult successWith(AiMessage successfulAiMessage, Object successfulResult) {
        return OutputGuardrailResult.successWith(successfulAiMessage, successfulResult);
    }

    /**
     * 产生非致命失败
     * Produces a non-fatal failure
     *
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     *
     * @return The result of a failed output guardrail validation.
     */
    default OutputGuardrailResult failure(String message) {
        return new OutputGuardrailResult(new OutputGuardrailResult.Failure(message), false);
    }

    /**
     * 产生非致命失败
     * Produces a non-fatal failure
     *
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     * @param cause
     *            The exception that caused this failure.
     *            导致此失败的异常
     *
     * @return The result of a failed output guardrail validation.
     */
    default OutputGuardrailResult failure(String message, Throwable cause) {
        return new OutputGuardrailResult(new OutputGuardrailResult.Failure(message, cause), false);
    }

    /**
     * 产生致命失败
     * Produces a fatal failure
     *
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation.
     */
    default OutputGuardrailResult fatal(String message) {
        return new OutputGuardrailResult(List.of(new OutputGuardrailResult.Failure(message)), true);
    }

    /**
     * 产生致命失败
     * Produces a fatal failure
     *
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     * @param cause
     *            The exception that caused this failure.
     *            导致此失败的异常
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation.
     */
    default OutputGuardrailResult fatal(String message, Throwable cause) {
        return new OutputGuardrailResult(List.of(new OutputGuardrailResult.Failure(message, cause)), true);
    }

    /**
     * 重试
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with the same user prompt.
     */
    default OutputGuardrailResult retry(String message) {
        return new OutputGuardrailResult(List.of(new OutputGuardrailResult.Failure(message, null, true)), true);
    }

    /**
     * 重试
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     * @param cause
     *            The exception that caused this failure.
     *            导致此失败的异常
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with the same user prompt.
     */
    default OutputGuardrailResult retry(String message, Throwable cause) {
        return new OutputGuardrailResult(List.of(new OutputGuardrailResult.Failure(message, cause, true)), true);
    }

    /**
     * 重新提示
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     * @param reprompt
     *            The new prompt to be used for the retry.
     *            用于重试的新提示
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with a new user prompt.
     */
    default OutputGuardrailResult reprompt(String message, String reprompt) {
        return new OutputGuardrailResult(
                List.of(new OutputGuardrailResult.Failure(message, null, true, reprompt)), true);
    }

    /**
     * 重新提示
     * @param message
     *            A message describing the failure.
     *            描述失败的消息
     * @param cause
     *            The exception that caused this failure.
     *            导致此失败的异常
     * @param reprompt
     *            The new prompt to be used for the retry.
     *            用于重试的新提示
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with a new user prompt.
     */
    default OutputGuardrailResult reprompt(String message, Throwable cause, String reprompt) {
        return new OutputGuardrailResult(
                List.of(new OutputGuardrailResult.Failure(message, cause, true, reprompt)), true);
    }
}
