package dev.langchain4j.classification;

import static dev.langchain4j.internal.ValidationUtils.ensureBetween;
import static dev.langchain4j.internal.ValidationUtils.ensureGreaterThanZero;
import static dev.langchain4j.internal.ValidationUtils.ensureNotBlank;
import static dev.langchain4j.internal.ValidationUtils.ensureNotEmpty;
import static dev.langchain4j.internal.ValidationUtils.ensureNotNull;
import static java.util.Comparator.comparingDouble;
import static java.util.stream.Collectors.toList;

import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.CosineSimilarity;
import dev.langchain4j.store.embedding.RelevanceScore;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 嵌入模型的文本分类器
 * 一个使用嵌入模型和预定义示例进行分类的文本分类器。
 * 分类是通过计算输入文本的嵌入与带标签示例文本的嵌入之间的相似度来执行的。
 * 每个标签的示例数量越多，分类质量就越高。
 * 借助大型语言模型（LLM）可以轻松生成示例。
 * A {@link TextClassifier} that uses an {@link EmbeddingModel} and predefined examples to perform classification.
 * Classification is performed by computing the similarity between the input text's embedding and the embeddings of labeled example texts.
 * The classification quality improves with a greater number of examples for each label.
 * Examples can be easily generated with the help of an LLM.
 * <p>
 * Example:
 * <pre>{@code
 * enum Sentiment {
 *     POSITIVE, NEUTRAL, NEGATIVE
 * }
 *
 *  Map<Sentiment, List<String>> examples = Map.of(
 *     POSITIVE, List.of("This is great!", "Wow, awesome!"),
 *     NEUTRAL,  List.of("Well, it's fine", "It's ok"),
 *     NEGATIVE, List.of("It is pretty bad", "Worst experience ever!")
 * );
 *
 * EmbeddingModel embeddingModel = new AllMiniLmL6V2QuantizedEmbeddingModel();
 *
 * TextClassifier<Sentiment> classifier = new EmbeddingModelTextClassifier<>(embeddingModel, examples);
 *
 * List<Sentiment> sentiments = classifier.classify("Awesome!");
 * System.out.println(sentiments); // [POSITIVE]
 * }</pre>
 *
 * @param <L> The type of the label (e.g., String, Enum, etc.)
 */
public class EmbeddingModelTextClassifier<L> implements TextClassifier<L> {

    /**
     * 嵌入模型
     */
    private final EmbeddingModel embeddingModel;
    /**
     * 评分标签到嵌入列表的映射表
     */
    private final Map<L, List<Embedding>> exampleEmbeddingsByLabel;
    /**
     * 最大的结果数量
     */
    private final int maxResults;
    /**
     * 最低分
     */
    private final double minScore;
    /**
     * 平均分到最高分的比率
     */
    private final double meanToMaxScoreRatio;

    /**
     * 使用默认值创建分类器，
     * 默认值为 maxResults（1）、minScore（0）和 meanToMaxScoreRatio（0.5）。
     * Creates a classifier with the default values for {@link #maxResults} (1), {@link #minScore} (0)
     * and {@link #meanToMaxScoreRatio} (0.5).
     *
     * @param embeddingModel  The embedding model used for embedding both the examples and the text to be classified.
     * @param examplesByLabel A map containing examples of texts for each label.
     *                        The more examples, the better. Examples can be easily generated by the LLM.
     */
    public EmbeddingModelTextClassifier(
            EmbeddingModel embeddingModel, Map<L, ? extends Collection<String>> examplesByLabel) {
        this(embeddingModel, examplesByLabel, 1, 0, 0.5);
    }

    /**
     * 创建一个分类器。
     * Creates a classifier.
     *
     * @param embeddingModel      The embedding model used for embedding both the examples and the text to be classified.
     * @param examplesByLabel     A map containing examples of texts for each label.
     *                            Providing more examples per label generally improves classification accuracy.
     *                            Examples can be easily generated by the LLM.
     * @param maxResults          The maximum number of labels to return for each classification.
     * @param minScore            The minimum similarity score required for classification, in the range [0..1].
     *                            Labels scoring lower than this value will be discarded.
     * @param meanToMaxScoreRatio A ratio, in the range [0..1], between the mean and max scores used for calculating
     *                            the final score.
     *                            During classification, the embeddings of examples for each label are compared to
     *                            the embedding of the text being classified.
     *                            This results in two metrics: the mean and max scores.
     *                            The mean score is the average similarity score for all examples associated with a given label.
     *                            The max score is the highest similarity score, corresponding to the example most
     *                            similar to the text being classified.
     *                            A value of 0 means that only the mean score will be used for ranking labels.
     *                            A value of 0.5 means that both scores will contribute equally to the final score.
     *                            A value of 1 means that only the max score will be used for ranking labels.
     */
    public EmbeddingModelTextClassifier(
            EmbeddingModel embeddingModel,
            Map<L, ? extends Collection<String>> examplesByLabel,
            int maxResults,
            double minScore,
            double meanToMaxScoreRatio) {
        this.embeddingModel = ensureNotNull(embeddingModel, "embeddingModel");
        ensureNotEmpty(examplesByLabel, "examplesByLabel");
        this.maxResults = ensureGreaterThanZero(maxResults, "maxResults");
        this.minScore = ensureBetween(minScore, 0.0, 1.0, "minScore");
        this.meanToMaxScoreRatio = ensureBetween(meanToMaxScoreRatio, 0.0, 1.0, "meanToMaxScoreRatio");

        this.exampleEmbeddingsByLabel = new HashMap<>();
        // 嵌入一系列文本段的文本内容
        examplesByLabel.forEach((label, examples) -> exampleEmbeddingsByLabel.put(
                label,
                embeddingModel
                        .embedAll(examples.stream().map(TextSegment::from).collect(toList()))
                        .content()));
    }

    /**
     * 对给定文本进行分类，并返回带有分数的标签。
     */
    @Override
    public ClassificationResult<L> classifyWithScores(String text) {
        ensureNotBlank(text, "text");

        // 嵌入文本
        Embedding textEmbedding = embeddingModel.embed(text).content();

        // 评分标签列表
        List<ScoredLabel<L>> scoredLabels = new ArrayList<>();
        exampleEmbeddingsByLabel.forEach((label, exampleEmbeddings) -> {
            // 平均分
            double meanScore = 0;
            // 最高分
            double maxScore = 0;
            for (Embedding exampleEmbedding : exampleEmbeddings) {
                // 计算两个向量之间的余弦相似度
                double cosineSimilarity = CosineSimilarity.between(textEmbedding, exampleEmbedding);
                // 将余弦相似度转换为相关度评分
                double score = RelevanceScore.fromCosineSimilarity(cosineSimilarity);
                meanScore += score;
                maxScore = Math.max(score, maxScore);
            }
            meanScore /= exampleEmbeddings.size();

            // 综合得分
            double aggregateScore = aggregatedScore(meanScore, maxScore);
            if (aggregateScore >= minScore) {
                scoredLabels.add(new ScoredLabel<>(label, aggregateScore));
            }
        });

        return new ClassificationResult<>(scoredLabels.stream()
                // sorting in descending order to return highest score first
                .sorted(comparingDouble(classificationResult -> 1 - classificationResult.score()))
                .limit(maxResults)
                .collect(toList()));
    }

    private double aggregatedScore(double meanScore, double maxScore) {
        // 综合得分
        return (meanToMaxScoreRatio * meanScore) + ((1 - meanToMaxScoreRatio) * maxScore);
    }
}
